name: Test Minitrice

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: faire les tests
        run: |
          # Comparer chaque fichier de test avec son fichier de résultat correspondant
          for i in {00..10}; do
            test_file="test/${i}-*.txt"
            result_file="results/${i}-*.txt"
            # Utiliser minitrice.py pour évaluer les expressions dans le fichier de test
            evaluated_test=$(awk '{print $0}' $test_file | python minitrice.py)
            # Lire les résultats attendus 
            expected_result=$(awk '{print $0}' $result_file)

            diff -u <(echo "$evaluated_test") <(echo "$expected_result")

            # Comparer les résultats évalués avec les résultats attendus
            paste <(echo "$evaluated_test") <(echo "$expected_result") | while IFS=$'\t' read -r eval_line exp_line; do
              if [ "$eval_line" != "$exp_line" ]; then
                echo "Différence trouvée !"
                echo "Évalué  : $eval_line"
                echo "Attendu : $exp_line"
                exit 1
              fi
            done
          done
          echo "Tous les résultats sont corrects !"
