name: Test Minitrice

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: faire les tests
        run: |
          # Comparer chaque fichier de test avec son fichier de résultat correspondant
          for i in {00..10}; do
            test_file="test/${i}-*.txt"
            result_file="results/${i}-*.txt"
            # Utiliser minitrice.py pour évaluer les expressions dans le fichier de test
            evaluated_test=$(awk '{print $0}' $test_file | python minitrice.py 2>&1)
            exit_code=$?  # Capture le code de sortie de minitrice.py
            # Lire les résultats attendus 
            expected_result=$(awk '{printf "%.1f\n", $1}' $result_file)

            echo "Test file : $test_file"
            echo "Result file : $result_file"
            echo "Évalué : $evaluated_test"
            echo "Attendu : $expected_result"


            # Comparer les résultats évalués avec les résultats attendus
            if [ $exit_code -ne 0 ]; then
            # Vérifier si l'erreur est attendue
              if [ "$evaluated_test" != "$expected_result" ]; then
                echo "Erreur non prévue !"
                echo "Erreur reçue : $evaluated_test"
                echo "Erreur attendue : $expected_result"
                exit 1
              else
                # L'erreur correspond à l'erreur attendue, donc c'est un succès
                echo "Erreur attendue pour $i : $evaluated_test"
              fi
           else
              # Comparer les résultats après formatage
              if ! diff <(echo "$evaluated_test") <(echo "$expected_result"); then
                echo "Les résultats ne correspondent pas pour le fichier $i"
                exit 1
              fi
            fi
          done
          echo "Tous les résultats sont corrects !"
