name: Test Minitrice

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: faire les tests
        run: |
          # Comparer chaque fichier de test avec son fichier de résultat correspondant
          for i in {00..10}; do
            test_file="test/${i}-*.txt"
            result_file="results/${i}-*.txt"
            # Utiliser minitrice.py pour évaluer les expressions dans le fichier de test
            evaluated_test=$(awk '{print $0}' $test_file) | python minitrice.py)
            # Lire les résultats attendus
            expected_result=$(awk '{print $0}' "$result_file")
            # Comparer les résultats évalués avec les résultats attendus
            if [ "$evaluated_test" != "$expected_result" ]; then
              echo "Les résultats ne correspondent pas pour le fichier $i"
              echo "Résultat évalué : $evaluated_test"
              echo "Résultat attendu : $expected_result"
              exit 1
            fi
          done
          echo "Tous les résultats sont corrects !"
