name: Test Minitrice

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: faire les tests
        run: |
          # Comparer chaque fichier de test avec son fichier de résultat correspondant
          for i in {00..10}; do
            test_file="test/${i}-*.txt"
            result_file="results/${i}-*.txt"
            output_file="output_${i}.txt"

            # Exécuter minitrice.py avec le fichier de test et stocker le résultat
            python minitrice.py < "$test_file" > "$output_file"

            # Comparer les résultats en s'assurant que les nombres entiers et flottants sont traités de manière équivalente
            if ! diff -q <(sort <(awk '{printf "%.1f\n", $1}' "$output_file")) <(sort <(awk '{printf "%.1f\n", $1}' "$result_file")); then
              echo "Les résultats ne correspondent pas pour le fichier $i"
              diff "$output_file" "$result_file"
              exit 1
            fi
          done

          echo "Tous les résultats sont corrects !"
